name: ai_farmers_companion
description: "AI Farmer's Companion: Multilingual agricultural support for Ethiopian farmers."
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Theming
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0 # For custom fonts if needed

  # State Management (choose one or combine)
  flutter_bloc: ^8.1.3 # Example: BLoC
  # provider: ^6.0.5 # Example: Provider

  # Networking
  http: ^1.1.0
  connectivity_plus: ^5.0.1 # Check network status

  # Local Storage
  shared_preferences: ^2.2.2 # Simple key-value storage
  # sqflite: ^2.3.0 # For local SQL database
  # path_provider: ^2.1.1 # Access to file system paths

  # Permissions
  permission_handler: ^11.0.1

  # AI & ML Related (placeholders, specific packages depend on implementation)
  # tflite_flutter: # For TensorFlow Lite models
  # onnxruntime_flutter: # For ONNX models

  # Voice & Audio
  speech_to_text: ^6.6.0 # Device STT capabilities
  # flutter_tts: ^3.8.3 # Device TTS capabilities
  # audioplayers: ^5.2.1 # For playing audio feedback/TTS output
  record: ^7.0.0 # Add audio recording package

  # Image Handling
  image_picker: ^1.0.4 # For selecting images from gallery/camera

  # Internationalization (i18n)
  intl: ^0.20.2 # For date/number formatting, etc.
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  supabase_flutter: ^2.3.2

  # Utilities
  # equatable: ^2.0.5 # For value equality in BLoC/models
  # get_it: ^7.6.4 # Service locator
  # dartz: ^0.10.1 # Functional programming helpers

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
